spring.application.name=spotify-liked-songs
spring.docker.compose.enabled=false

# Server
server.port=8081

# Spotify OAuth2 Config
spring.security.oauth2.client.registration.spotify.client-id=0f8e7b7eb70648de8e840962f0d48b24
spring.security.oauth2.client.registration.spotify.client-secret=cd4151a343d049f6bfaa56998a42e78f
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.spotify.scope=user-library-read

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me